name: Publish dev image
run-name: Publish dev image
on:
  push:
    branches:
      dev*

jobs:
  build-and-deploy:
    name: Build and deploy
    uses: ./.github/workflows/_deploy_to_docker.yml
    with:
      version: "0.0.1"
      release_train: "dev"
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}